#!/usr/bin/env bash
# A Bash script that will display information about the subdomains

# dig command for dns query, pipped to grep command to match the line containing #
#'ANSWER SECTION:', -A1 flag to include line after matching.
 
dns_config () {
  ANSWER=$(dig $2 | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
  echo "The subdomain $1 is a $(echo $ANSWER | awk '{print $4}') record and points to $(echo $ANSWER | awk '{print $5}')"}

if [ "$#" == 1 ]
then
  subdomains=('www' 'lb-01' 'web-01' 'web-02')
  for i in "${subdomains[@]}"; do
    CONCAT="$i.$1"
    dns_config $i $CONCAT
  done
else
  CONCAT="$2.$1"
  dns_config $2 $CONCAT
fi
