#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

#The configuration defines a frontend named skydar-frontend that listens on all network interfaces
# (*) on port 80 (bind *:80). It also sets the mode to http,
# indicating that the incoming traffic is expected to use the HTTP protocol.
# The check option at the end of each server line specifies that HAProxy should check the server's health status
# before forwarding traffic to it. This ensures that HAProxy only forwards traffic to healthy servers.
# The backend backend is defined with the balance roundrobin directive, which instructs HAProxy to distribute
# incoming traffic across all servers defined in the backend in a round-robin fashion.

frontend skydar-frontend
        bind *:80
        mode http
        default_backend skydar-backend
backend skydar-backend
        balance roundrobin
        server 63210-web-01 34.201.165.238 check
        server 63210-web-02 100.26.217.108 check

# most explaination from first file on echo, sudo, tee etc.
# -a option to append a file rather than overwriting
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
